title: "Toheeb Aduramomi Jimoh"
email: jimoh.toheeb@aims.ac.rw
description: "This personal website detail my career and professional experience."
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://toheebadura.github.io" # the base hostname & protocol for your site
twitter_username: toheebadura
github_username: toheebadura
linkedin_username: toheebadura

